# Generated by Django 3.0.5 on 2023-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
