# Generated by Django 3.0.5 on 2023-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_teacherextra_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
