# Generated by Django 3.0.5 on 2023-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20230715_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
